"""empty message

Revision ID: 664c872b0659
Revises: a2a951b2f6b5
Create Date: 2022-05-31 09:05:58.312530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664c872b0659'
down_revision = 'a2a951b2f6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
